//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkrApiDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResult
    {
        public int TestId { get; set; }
        public int StudentNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int MarksAvailable { get; set; }
        public int MarksObtained { get; set; }
        public System.DateTime ScannedOn { get; set; }
    }
}
